version: '3.8'

services:
  hyperhash:
    image: datadiego808/hyperhash
    container_name: hyperhash
    ports:
      - "3000:3000"
    networks:
      - webnet
    environment:
      - NODE_ENV=production
      - COOKIE_SECRET=secret

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew --nginx; sleep 12h & wait $${!}; done;'
    command: certonly --nginx --non-interactive --agree-tos --email your_email@example.com -d your_domain.com

networks:
  webnet:
    driver: bridge
